feat: Port is serializable
CQCL-DEV/hugr pull request #489
Opened 2023-09-04 11:13 UTC by lmondada

I need something like this to be able to serialize pattern matcher in TKET2 (more specifically: to serialize predicates for matching). I'm not sure this is the right approach or you'd rather I expose a different serialization API in HUGR for this purpose.

2023-09-04 11:15 UTC, ss2165 approved these changes

2023-09-04 11:15 UTC, ss2165 commented
Do you not need to derive Serialize/Deserialize if you mark as transparent?

2023-09-04 12:37 UTC, ss2165 requested changes

2023-09-05 07:59 UTC, lmondada commented on src/hugr.rs
>  #[derive(Clone, Copy, PartialEq, PartialOrd, Eq, Ord, Hash, Default, Debug, From)]
Yes you're right!

2023-09-05 13:45 UTC, aborgna-q approved these changes

2023-09-05 13:50 UTC, merged